// Shared types for the backend and (via `import type`) the web UI.

export type LineRange = [number, number];

export interface HunkMember {
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
}

/** A single parsed hunk, before grouping. */
export interface RawHunk {
  id: string;
  file: string;
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
  context: string;
  diff: string;
}

export type AiNoteKind = 'initial' | 'context' | 'investigation' | 'error';

/** A group of one or more adjacent hunks in the same file. */
export interface Chunk extends RawHunk {
  members: HunkMember[];
  /**
   * Only set by `--mock-ai` (`attachMockNotes`), which fills in placeholder
   * `id`/`chunk_id`/`created_at` values rather than using a separate
   * in-memory-only shape — these notes are never written to
   * `ReviewState.notes`, so the fake ids never collide with real ones.
   */
  ai_notes?: StoredNote[];
}

export type Platform = 'github' | 'gitlab';

export interface PrRef {
  owner: string;   // for GitLab: full namespace, e.g. "group/subgroup"
  repo: string;
  number: number;
  platform: Platform;
}

export interface PrMeta {
  title: string;
  author: string;
  base_ref: string;
  head_ref: string;
  is_draft: boolean;
  url: string;
  head_sha: string;
  body: string;
}

export interface JiraIssue {
  key: string;
  summary: string;
  status: string;
  type: string;
  description: string;
  url: string;
  epic_key?: string;
}

/** Jira background for the overview page (or why it's unavailable). */
export interface JiraContext {
  available: boolean;
  reason?: string;
  setup_hint?: string;
  keys: string[];
  issues: JiraIssue[];
  epic?: JiraIssue | null;
}

/** Intro context shown on the first (overview) page. */
export interface Overview {
  jira: JiraContext;
}

/** The payload served at /api/review and consumed by the UI. */
export interface Review {
  pr: PrRef;
  meta: PrMeta;
  chunks: Chunk[];
  overview: Overview;
  generated_at: string;
}

/** Pseudo-chunk id for notes/summary attached to the overview page. */
export const OVERVIEW_ID = '__overview__';

export type Side = 'RIGHT' | 'LEFT';

/** GitHub PR review events. */
export type Verdict = 'APPROVE' | 'COMMENT' | 'REQUEST_CHANGES';
export const VERDICTS: readonly Verdict[] = [
  'APPROVE',
  'COMMENT',
  'REQUEST_CHANGES',
];

/** GitLab MR review events (approvals are separate from discussion notes). */
export type GitLabVerdict = 'approve' | 'comment';
export const GITLAB_VERDICTS: readonly GitLabVerdict[] = ['approve', 'comment'];

/** A reviewer's drafted comment. A null anchor = comment on the whole chunk. */
export interface DraftComment {
  id: string;
  /** Last-known chunk id. Not trustworthy for lookup when `displaced` is true. */
  chunk_id: string;
  side: Side | null;
  line: number | null;
  body: string;
  /** Snapshot of the anchored chunk's `file` at anchor time (Anchor Reconciliation). */
  file: string;
  /** Snapshot of the anchored chunk's `hunk_header` at anchor time. */
  hunk_header: string;
  /** Set when the snapshot no longer matches any chunk on reload; cleared by `reanchor_comment`. */
  displaced: boolean;
  created_at: string;
  updated_at: string;
}

export type AiProvider = 'claude' | 'codex';

/** Global AI provider/model selection persisted outside any one review. */
export interface AiProviderConfig {
  provider: AiProvider;
  claude_model?: string;
  codex_model?: string;
  updated_at: string;
}

/** An AI note generated by the configured AI provider and persisted in state. */
export interface StoredNote {
  id: string;
  /** Or OVERVIEW_ID. Last-known chunk id when `displaced` is true. */
  chunk_id: string;
  kind: AiNoteKind;
  prompt?: string;
  body: string;
  suggested_action?: string;
  /** Snapshot of the anchored chunk's `file` at creation time. Unset for overview notes. */
  file?: string;
  /** Snapshot of the anchored chunk's `hunk_header` at creation time. Unset for overview notes. */
  hunk_header?: string;
  /** Set when the snapshot no longer matches any chunk on reload. Overview notes are never displaced. */
  displaced?: boolean;
  created_at: string;
}

/** A flagged chunk, with the same anchor-snapshot fields as `DraftComment`/
 *  `StoredNote` so flags participate in Anchor Reconciliation. Replaces a
 *  bare chunk-id string, which couldn't carry a snapshot. */
export interface FlaggedEntry {
  /** Last-known chunk id. Not trustworthy for lookup when `displaced` is true. */
  chunk_id: string;
  file: string;
  hunk_header: string;
  /** Set by reconciliation on load. Unlike `DraftComment`, a flag has no
   *  re-anchor action — a displaced flag can only be shown as displaced or unflagged. */
  displaced: boolean;
}

export const STATE_VERSION = 2;

/** GitLab-only submission progress — see `ReviewState.gitlab_submit_progress`. */
export interface GitLabSubmitProgress {
  posted_comment_ids: string[];
  note_posted: boolean;
  approved: boolean;
}

/** Persisted review state (drafts, flags, viewed, AI notes). Resumed on restart. */
export interface ReviewState {
  version: number;
  pr: PrRef;
  /** Cached PR metadata so the reviews listing can show titles without re-fetching. */
  meta?: PrMeta;
  head_sha: string;
  started_at: string;
  comments: DraftComment[];
  flagged: FlaggedEntry[];
  viewed: string[]; // chunk ids
  notes: StoredNote[];
  /** Set once the review has been published to GitHub. */
  submitted?: { at: string; verdict: string; url?: string };
  /** GitLab only — tracks which parts of a submission already succeeded, so
   *  a retry after partial failure skips them instead of reposting
   *  duplicates. Cleared once a submission fully succeeds, the same moment
   *  `submitted` is stamped. GitHub's single-POST review is atomic and
   *  never uses this field. */
  gitlab_submit_progress?: GitLabSubmitProgress;
}

export interface ReviewSummary {
  pr: PrRef;
  meta?: PrMeta;
  head_sha: string;
  started_at: string;
  comment_count: number;
  flagged_count: number;
  viewed_count: number;
  submitted?: { at: string; verdict: string; url?: string };
}

/** Mutations the UI POSTs to /api/action (and that the Claude route applies). */
export type Action =
  | {
      type: 'add_comment';
      chunk_id: string;
      side: Side | null;
      line: number | null;
      body: string;
      file: string;
      hunk_header: string;
    }
  | { type: 'update_comment'; id: string; body: string }
  | { type: 'delete_comment'; id: string }
  | {
      type: 'reanchor_comment';
      id: string;
      chunk_id: string;
      side: Side | null;
      line: number | null;
      file: string;
      hunk_header: string;
    }
  | { type: 'toggle_flag'; chunk_id: string; file: string; hunk_header: string }
  | { type: 'set_viewed'; chunk_id: string; viewed: boolean }
  | {
      type: 'add_note';
      chunk_id: string;
      kind: AiNoteKind;
      prompt?: string;
      body: string;
      suggested_action?: string;
      file?: string;
      hunk_header?: string;
    }
  | { type: 'delete_note'; id: string };

export interface ReviewComment {
  path: string;
  body: string;
  side: Side;
  line: number;
}

export interface ReviewPayload {
  event: Verdict;
  body: string;
  commit_id: string;
  comments: ReviewComment[];
}

/** Per-repo (not per-PR) choice of how much filesystem/repo access the
 *  headless Claude investigation gets — see `infrastructure.md`'s "Repo
 *  Investigation Access" section. Persisted keyed by `platform:owner/repo`
 *  in a single `investigation-config.json` map, not one file per entry. */
export interface InvestigationConfig {
  platform: Platform;
  owner: string;
  repo: string;
  mode: 'none' | 'local-path' | 'api' | 'temp-clone' | 'always-clone';
  /** Only set (and only meaningful) when `mode` is `'local-path'`. */
  local_path?: string;
  /** Only set for `'temp-clone'`/`'always-clone'` — computed, not reviewer-supplied. */
  clone_path?: string;
  /** ISO, set when the mode is first chosen. */
  chosen_at: string;
  /** ISO, updated each time an investigation call actually uses this config. */
  last_used?: string;
}

/** Response from a submit adapter (`submitReview`/`submitGitLabReview`). The
 *  `/api/submit` route handler adds a `state` field on top of this before it
 *  reaches the client — see `web/src/api.ts`'s `SubmitResponse`, which shares
 *  this type rather than re-declaring it. */
export interface SubmitResult {
  ok: boolean;
  /** Review permalink on success. */
  html_url?: string;
  /** Set when the head SHA the comments were drafted against is gone. */
  stale?: { old: string; new_head: string; inline_count: number };
  /** Errors from individual GitLab discussion POSTs (partial success). */
  comment_errors?: Array<{ path: string; line: number | null; error: string }>;
  /** gh/glab stderr (or a synthesized message) on a non-stale failure. */
  error?: string;
  /** Echoed on failure so the UI can offer a manual-submit fallback. Never
   *  serialized to the client (the route handler strips it before reply). */
  payload?: ReviewPayload;
}
