// Shared types for the backend and (via `import type`) the web UI.

export type LineRange = [number, number];

export interface HunkMember {
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
}

/** A single parsed hunk, before grouping. */
export interface RawHunk {
  id: string;
  file: string;
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
  context: string;
  diff: string;
}

export type AiNoteKind = 'initial' | 'context' | 'investigation' | 'error';

/** A group of one or more adjacent hunks in the same file. */
export interface Chunk extends RawHunk {
  members: HunkMember[];
  /**
   * Only set by `--mock-ai` (`attachMockNotes`), which fills in placeholder
   * `id`/`chunk_id`/`created_at` values rather than using a separate
   * in-memory-only shape — these notes are never written to
   * `ReviewState.notes`, so the fake ids never collide with real ones.
   */
  ai_notes?: StoredNote[];
}

export type Platform = 'github' | 'gitlab';

export interface PrRef {
  owner: string;   // for GitLab: full namespace, e.g. "group/subgroup"
  repo: string;
  number: number;
  platform: Platform;
}

export interface PrMeta {
  title: string;
  author: string;
  base_ref: string;
  head_ref: string;
  is_draft: boolean;
  url: string;
  head_sha: string;
  body: string;
}

export interface JiraIssue {
  key: string;
  summary: string;
  status: string;
  type: string;
  description: string;
  url: string;
  epic_key?: string;
}

/** Jira background for the overview page (or why it's unavailable). */
export interface JiraContext {
  available: boolean;
  reason?: string;
  setup_hint?: string;
  keys: string[];
  issues: JiraIssue[];
  epic?: JiraIssue | null;
}

/** Intro context shown on the first (overview) page. */
export interface Overview {
  jira: JiraContext;
}

/** The payload served at /api/review and consumed by the UI. */
export interface Review {
  pr: PrRef;
  meta: PrMeta;
  chunks: Chunk[];
  overview: Overview;
  generated_at: string;
}

/** Pseudo-chunk id for notes/summary attached to the overview page. */
export const OVERVIEW_ID = '__overview__';

export type Side = 'RIGHT' | 'LEFT';

/** GitHub PR review events. */
export type Verdict = 'APPROVE' | 'COMMENT' | 'REQUEST_CHANGES';
export const VERDICTS: readonly Verdict[] = [
  'APPROVE',
  'COMMENT',
  'REQUEST_CHANGES',
];

/** GitLab MR review events (approvals are separate from discussion notes). */
export type GitLabVerdict = 'approve' | 'comment';
export const GITLAB_VERDICTS: readonly GitLabVerdict[] = ['approve', 'comment'];

/** A reviewer's drafted comment. A null anchor = comment on the whole chunk. */
export interface DraftComment {
  id: string;
  chunk_id: string;
  side: Side | null;
  line: number | null;
  body: string;
  created_at: string;
  updated_at: string;
}

/** An AI note generated by Claude and persisted in state. */
export interface StoredNote {
  id: string;
  chunk_id: string;
  kind: AiNoteKind;
  prompt?: string;
  body: string;
  suggested_action?: string;
  created_at: string;
}

export const STATE_VERSION = 1;

/** Persisted review state (drafts, flags, viewed, AI notes). Resumed on restart. */
export interface ReviewState {
  version: number;
  pr: PrRef;
  /** Cached PR metadata so the reviews listing can show titles without re-fetching. */
  meta?: PrMeta;
  head_sha: string;
  started_at: string;
  comments: DraftComment[];
  flagged: string[]; // chunk ids
  viewed: string[]; // chunk ids
  notes: StoredNote[];
  /** Set once the review has been published to GitHub. */
  submitted?: { at: string; verdict: string; url?: string };
}

export interface ReviewSummary {
  pr: PrRef;
  meta?: PrMeta;
  head_sha: string;
  started_at: string;
  comment_count: number;
  flagged_count: number;
  viewed_count: number;
  submitted?: { at: string; verdict: string; url?: string };
}

/** Mutations the UI POSTs to /api/action (and that the Claude route applies). */
export type Action =
  | {
      type: 'add_comment';
      chunk_id: string;
      side: Side | null;
      line: number | null;
      body: string;
    }
  | { type: 'update_comment'; id: string; body: string }
  | { type: 'delete_comment'; id: string }
  | { type: 'toggle_flag'; chunk_id: string }
  | { type: 'set_viewed'; chunk_id: string; viewed: boolean }
  | {
      type: 'add_note';
      chunk_id: string;
      kind: AiNoteKind;
      prompt?: string;
      body: string;
      suggested_action?: string;
    }
  | { type: 'delete_note'; id: string };

export interface ReviewComment {
  path: string;
  body: string;
  side: Side;
  line: number;
}

export interface ReviewPayload {
  event: Verdict;
  body: string;
  commit_id: string;
  comments: ReviewComment[];
}

/** Response from a submit adapter (`submitReview`/`submitGitLabReview`). The
 *  `/api/submit` route handler adds a `state` field on top of this before it
 *  reaches the client — see `web/src/api.ts`'s `SubmitResponse`, which shares
 *  this type rather than re-declaring it. */
export interface SubmitResult {
  ok: boolean;
  /** Review permalink on success. */
  html_url?: string;
  /** Set when the head SHA the comments were drafted against is gone. */
  stale?: { old: string; new_head: string; inline_count: number };
  /** Errors from individual GitLab discussion POSTs (partial success). */
  comment_errors?: Array<{ path: string; line: number | null; error: string }>;
  /** gh/glab stderr (or a synthesized message) on a non-stale failure. */
  error?: string;
  /** Echoed on failure so the UI can offer a manual-submit fallback. Never
   *  serialized to the client (the route handler strips it before reply). */
  payload?: ReviewPayload;
}
