// Shared types for the backend and (via `import type`) the web UI.

export type LineRange = [number, number];

export interface HunkMember {
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
}

/** A single parsed hunk, before grouping. */
export interface RawHunk {
  id: string;
  file: string;
  hunk_header: string;
  old_range: LineRange;
  new_range: LineRange;
  context: string;
  diff: string;
}

export type AiNoteKind = 'initial' | 'context' | 'investigation' | 'error';

/** A piece of AI commentary attached to a chunk. */
export interface AiNote {
  kind: AiNoteKind;
  body: string;
  /** For `investigation` notes: the question the user asked. */
  prompt?: string;
  /** A concrete next step the reviewer could take (on `initial` notes). */
  suggested_action?: string;
}

/** A group of one or more adjacent hunks in the same file. */
export interface Chunk extends RawHunk {
  members: HunkMember[];
  ai_notes?: AiNote[];
}

export interface PrRef {
  owner: string;
  repo: string;
  number: number;
}

export interface PrMeta {
  title: string;
  author: string;
  base_ref: string;
  head_ref: string;
  is_draft: boolean;
  url: string;
  head_sha: string;
  body: string;
}

export interface JiraIssue {
  key: string;
  summary: string;
  status: string;
  type: string;
  description: string;
  url: string;
  epic_key?: string;
}

/** Jira background for the overview page (or why it's unavailable). */
export interface JiraContext {
  available: boolean;
  reason?: string;
  setup_hint?: string;
  keys: string[];
  issues: JiraIssue[];
  epic?: JiraIssue | null;
}

/** Intro context shown on the first (overview) page. */
export interface Overview {
  jira: JiraContext;
}

/** The payload served at /api/review and consumed by the UI. */
export interface Review {
  pr: PrRef;
  meta: PrMeta;
  chunks: Chunk[];
  overview: Overview;
  generated_at: string;
}

/** Pseudo-chunk id for notes/summary attached to the overview page. */
export const OVERVIEW_ID = '__overview__';

export type Side = 'RIGHT' | 'LEFT';

/** A reviewer's drafted comment. A null anchor = comment on the whole chunk. */
export interface DraftComment {
  id: string;
  chunk_id: string;
  side: Side | null;
  line: number | null;
  body: string;
  created_at: string;
  updated_at: string;
}

/** An AI note generated by Claude and persisted in state. */
export interface StoredNote {
  id: string;
  chunk_id: string;
  kind: AiNoteKind;
  prompt?: string;
  body: string;
  suggested_action?: string;
  created_at: string;
}

/** Persisted review state (drafts, flags, viewed, AI notes). Resumed on restart. */
export interface ReviewState {
  pr: PrRef;
  head_sha: string;
  started_at: string;
  comments: DraftComment[];
  flagged: string[]; // chunk ids
  viewed: string[]; // chunk ids
  notes: StoredNote[];
}

/** Mutations the UI POSTs to /api/action (and that the Claude route applies). */
export type Action =
  | { type: 'add_comment'; chunk_id: string; side: Side | null; line: number | null; body: string }
  | { type: 'update_comment'; id: string; body: string }
  | { type: 'delete_comment'; id: string }
  | { type: 'toggle_flag'; chunk_id: string }
  | { type: 'set_viewed'; chunk_id: string; viewed: boolean }
  | {
      type: 'add_note';
      chunk_id: string;
      kind: AiNoteKind;
      prompt?: string;
      body: string;
      suggested_action?: string;
    }
  | { type: 'delete_note'; id: string };
